### ISSUE TITLE
Transient property in constructor of data class

### ISSUE THREAD

**Issue by Burtan** [objectbox/objectbox-java#1074]
**Describe the bug**
The following data class throws the error that a full constructor is missing. However the Transient property isHappy has a default value and therefore the persisted data is sufficient to instantiate the class Person(name = "John").
```
@Entity
data class Person(val name: String, @Transient val isHappy: Boolean = true) {
    @Id var id: Long = 0
}
```

**Basic info (please complete the following information):**
 - ObjectBox version (are you using the latest version?): Android Api 31, kotlin 1.6.21, objectbox-java 3.2.1
 - Reproducibility: always

**To Reproduce**
Try to create the class mentioned above

**Expected behavior**
No error.

**Comment by greenrobot-team** [comment]
You need to add default values for all constructor parameters so Kotlin creates a default constructor that ObjectBox can call, see https://docs.objectbox.io/getting-started#define-entity-classes

The issue is that for this class Kotlin will not create a constructor that just accepts a single parameter (e.g. inspect using IntelliJ and Tools > Kotlin > Show Kotlin Bytecode and then Decompile). ObjectBox looks for a default constructor (no arguments) or a constructor having parameters for all properties.

**Comment by Burtan** [comment]
Ah thanks :-).
