### ISSUE TITLE
How to migrate. sqlite or. db file contents to. mdb

### ISSUE THREAD

**Issue by LiuYanshan63** [objectbox/objectbox-java#1107]
have . sqlite or. db file
need show my app，my app use objectbox

**Comment by greenrobot-team** [comment]
There is no file migration tool if you are referring to that. Note that just because the file extension is `mdb` does not mean that ObjectBox uses the Microsoft Access Database format.

To migrate data, write code that reads from the database file, creates objects annotated with ObjectBox annotations and puts them.
