### ISSUE TITLE
Native heap increases when we have indexing for tables

### ISSUE THREAD

**Issue by AmareshChannalli** [objectbox/objectbox-java#1177]
### Build info

- ObjectBox version: [e.g. 2.6.0]
- OS: [e.g. Android 7 

### Steps to reproduce

1. Create an ObjectBox  with version 2.6.0
2. Create a table and add indexing
3. After some time it is noticed that native heap is increasing at very high rate (20mb per day)
4. If there is no indexing on Object box then native heap increase in very minimum (1mb per day)

### Expected behavior

Native heap should not increased when there is indexing in table.

### Actual behavior

Native heap is increased at very high rate when there is indexing in table.

### Code

<details><summary>Code</summary>

```java
@Entity
public class HisItem
{
    @Id
    long id;
    
    @Index
    String rec;
    
    long date;
    
    Double val;
    
    @Index
    boolean syncStatus;
    
    @Transient
    public Boolean initialized = true;
    
    public HisItem(){
    }

    public HisItem(long id, Date date, Double val) {
        this.id = id;
        this.date = date.getTime();
        this.val = val;
    }
    
    public HisItem(long id, Date date, Double val, Boolean initialized) {
        this.id = id;
        this.date = date.getTime();
        this.val = val;
        this.initialized = initialized;
    }
```

</details>

### Logs, stack traces

_TODO Add relevant logs, a stack trace or crash report._

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by greenrobot-team** [comment]
Thanks for reporting. However, version 2.6.0 is from 2020 and there have been many releases and changes since. Can you try to upgrade to the latest version (currently 3.8.0) and let us know if the issue persists then?

**Comment by amareshC** [comment]
We dont want to update to latest object-box version, is it possible to give any resolution for the issue

**Comment by greenrobot-team** [comment]
If the issue is with your code, you are best suited to diagnose and fix it. If the issue is with ObjectBox, it will require updating to the latest version of ObjectBox in any case?

Anyhow, can you provide an analysis of the native heap (e.g. memory allocations)?

> After some time it is noticed that native heap is increasing

This does not really help us to locate the issue. Can you provide code snippets of what the code is doing? E.g. one could write a test that is doing that thing in a loop to more quickly see the heap growing. Then one could do a memory analysis to isolate the issue.
