### ISSUE TITLE
ObjectBox Data Browser with Relations

### ISSUE THREAD

**Issue by fgustovo** [objectbox/objectbox-java#327]
## Issue Basics
- ObjectBox version (are using the latest version?): *1.3.4*
- Reproducibility: *[always]*

### Description
ObjectBox Data Browser doesnt show relations but when i click download all button, json file inclues ids of relations.

### Code

![image](https://user-images.githubusercontent.com/24546039/34667268-67f3f1f6-f479-11e7-8de0-fa94bbb4132e.png)

downladed JSON

> {
>  "objects": [
>   {"id": 123, "trackId": 14},
>   {"id": 124, "trackId": 15},
>   {"id": 125, "trackId": 18}
>  ]
> }

## Entities
```@Entity
public class CurrentTrackList {
    @Id
    public long id;

    public ToOne<Track> track;

    public CurrentTrackList() {
    }

-----------

@Entity
public class Track {
    @Id
    public long id;
    public String title;
    public String artist;
}

**Comment by greenrobot-team** [comment]
OK, just to clarify: it currently does show the ID of the target. In this case the ID of the track. This is cut off from your screenshot and should be visible right next to the id column.

This is also the same data that is returned as JSON and stored inside the database. So there is no difference there.

Do you expect that the whole track entity is shown instead of its ID? Or possibly a link to the related track?
-ut

**Comment by fgustovo** [comment]
Now i checked, it is (track id) shown. But its interesting. it was not shown when i open issue.
maybe this bug occurres only sometimes. You can close issue. if i see problem again i will write. 
thanks.
