### ISSUE TITLE
java.lang.RuntimeException: Could not init Android base dir at /data/data/<package>/files/objectbox

### ISSUE THREAD

**Issue by Oo121oO** [objectbox/objectbox-java#404]
java.lang.RuntimeException: Could not init Android base dir at /data/data/<package>/files/objectbox
	at io.objectbox.b.a(BoxStoreBuilder.java:161)

some poor devices have this problem. poor ROM will lead to this.

available rom : {"RAM":327804,"ROM":36364,"SD":0}

**Comment by greenrobot-team** [comment]
This exception is thrown if [ObjectBox fails to create the database directory](https://github.com/objectbox/objectbox-java/blob/master/objectbox-java/src/main/java/io/objectbox/BoxStoreBuilder.java#L180-L181) in the private storage directory of the app. This typically happens if your app uses the same ObjectBox database from multiple processes (not threads).

If you are sure this is due to low storage, you might want to add a check and show a warning to the user.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
