### ISSUE TITLE
Duplicate datas problem

### ISSUE THREAD

**Issue by feer921** [objectbox/objectbox-java#473]
First, thanks for provider a so powerful Database framwork!
Due to just "id" is the table primary key,so,if the datas are requested from Http server,and those datas have no default id,thus cause repeated addition.
How to avoid this problem??

**Comment by greenrobot-team** [comment]
Then you need to enforce a unique property yourself. For example by adding an `@Index` to a `String` property, then querying by that id instead of the ObjectBox assigned ID. See the [docs section about Object IDs](http://objectbox.io/documentation/entity-annotations/#Object_IDs_Id).

Please re-open if this did not answer your question. -ut
