### ISSUE TITLE
How .put() updates entities 

### ISSUE THREAD

**Issue by liquidiert** [objectbox/objectbox-java#474]
Hey there,
I'm having a more general question. How exactly is the .put function updating entities when changing them? Because I am experiencing, that it creates a new instance in the box, with a different Id and the changes I made, while the old one still exists...

**Comment by greenrobot-team** [comment]
Make sure to set the correct ID of the entity you want to modify. If it is set to `0` ObjectBox will assign the next available ID and create a new entity instead of updating an existing one. See the [object IDs docs for more info](http://objectbox.io/documentation/object-ids/).

Please re-open if this did not answer your question. -ut
