### ISSUE TITLE
Can't save same data with ToMany (Kotlin)

### ISSUE THREAD

**Issue by HankLi0130** [objectbox/objectbox-java#528]
## Issue Basics
- ObjectBox version (are using the latest version?):  2.0.0
- Reproducibility: always

### Description
I'm using ObjectBox to save data. When I save the same data with ToMany, it only save the first one.

I write a test, the size of result.details is 1.

Can I save multiple same data with ToMany? How can I fix it?

Thanks for answer.

ObjectBox(version:2.0.0)
Android(target sdk version:27)
Kotlin(version:1.2.60)

### Code

```
@Test
fun orderDetailTest() {
    val orderBox: Box<Order> = store.boxFor()

    // 儲存兩個內容相同的資料
    val order = Order().apply {
        this.details.add(OrderDetail(productSpecName = "ABC"))
        this.details.add(OrderDetail(productSpecName = "ABC"))
    }

    val orderId = orderBox.put(order)

    val result = orderBox.get(orderId)

    assert(result.details.size == 2)
}
```

## Entities

```
@Entity
data class Order(@Id var id: Long = 0,
                 val createTime: Long = 0,
                 val total: Int = 0) {

    @Backlink(to = "order")
    lateinit var details: ToMany<OrderDetail>
}

@Entity
data class OrderDetail(@Id var id: Long = 0,
                       val productName: String = "",
                       val productSpecName: String = "",
                       val productSpecPrice: Int = 0,
                       val quantity: Int = 0,
                       val subtotal: Int = 0) {

    lateinit var order: ToOne<Order>
}
```

**Comment by HankLi0130** [comment]
I just remove the key word 'data' with entity, it's work!

How come?

**Comment by greenrobot-team** [comment]
[Kotlin data classes](https://kotlinlang.org/docs/reference/data-classes.html) provide among others a custom implementation for `hashCode()`. `ToMany` uses a `HashMap` to keep track of entities to add or remove. I guess you can see where this is going:

Based on the Kotlin data class implementation if two data classes have the same properties, their hash codes match. Now given this example with two identical `OrderDetail` data classes according to their `hashCode()`:
```
val order = Order().apply {
    this.details.add(OrderDetail(productSpecName = "ABC"))
    this.details.add(OrderDetail(productSpecName = "ABC"))
}
```
Two entities will be added to the `ToMany` list. However, the internal change tracking mechanism assumes that the second entity replaces the first one, because `HashMap` believes they are the same. Hence only one gets added.

Making `OrderDetail` a regular class drops the custom `hashCode()` implementation and everything works as expected.
-ut

**Comment by greenrobot-team** [comment]
Just to make this clear: this is the intended behavior, there is nothing particularly wrong here. Two data classes that share the same properties are considered to be "the same".
-ut

**Comment by HankLi0130** [comment]
Thanks for answer.

**Comment by amgadserry** [comment]
@greenrobot-team I think you should reconsider this because entities could have relations to different targets which is not considered by the hashCode of data classes which would result in different entities being treated as the same entity

**Comment by amgadserry** [comment]
For those who still have an issue with you could override hashCode function with ur own implementation make sure u consider all relations in ur implementation
