### ISSUE TITLE
gradle sync failed

### ISSUE THREAD

**Issue by zhang-weifu** [objectbox/objectbox-java#546]
project configuration:
![image](https://user-images.githubusercontent.com/15135267/44899710-1448fe00-ad35-11e8-918b-6fa494a180ce.png)
![image](https://user-images.githubusercontent.com/15135267/44899725-22971a00-ad35-11e8-8d3b-f5fc56b6a37b.png)

when the gradle sync project.
![image](https://user-images.githubusercontent.com/15135267/44899655-ef548b00-ad34-11e8-8d7b-2a4dcd59a72e.png)

any suggestion?

**Comment by zhang-weifu** [comment]
use android gradle plugin 3.1.4 can build success. but how can we config it  by 2.x gradle?

**Comment by greenrobot-team** [comment]
ObjectBox requires Android Gradle Plugin 3.0.0 or higher [since version 1.4.2](https://docs.objectbox.io/#v-1-4-2-2018-02-25).

I strongly recommend updating to the latest version of the Android Gradle Plugin (3.1.4 as of this comment): https://developer.android.com/studio/releases/gradle-plugin
-ut
