### ISSUE TITLE
deleteAllFiles not working

### ISSUE THREAD

**Issue by shubhamnandanwar** [objectbox/objectbox-java#595]
I am trying to delete whole objectbox database by following code -

`BoxStore.deleteAllFiles(getApplicationContext(), null);`

Due to ID mismatch I can not initialize BoxStore instance, so it seems the only way for me to delete the whole database.

I had debug the code and in the following function in BoxStore.java class, it's kind of stucking. I had commented the line where execution seems to stop.

```
private static boolean isFileOpen(String canonicalPath) {
        synchronized (openFiles) {
            int tries = 0;
            while (tries < 5 && openFiles.contains(canonicalPath)) {
                tries++;
                System.gc();
                
                //Does not executing after following line (Stucking in following function)
                System.runFinalization();
                System.gc();
                System.runFinalization();
                try {
                    openFiles.wait(100);
                } catch (InterruptedException e) {
                    // Ignore
                }
            }
            return openFiles.contains(canonicalPath);
        }
    }
```

And after 60 seconds, I am getting following exception

> Fatal Exception: java.util.concurrent.TimeoutException
> io.objectbox.BoxStore.finalize() timed out after 60 seconds

I am using latest version of objectbox and my intention for doing all this is to delete objectbox database and create a new one if ID mismatch exception occurs to users.

Device: Redmi 3s
Android OS - 6.0.1

**Comment by greenrobot-team** [comment]
Quoting Crashlytics info on this:

"This is an Android system-level crash that happened because JVM garbage collection took too long. It was likely caused by an incorrect clean-up of native resources, or because garbage collection occurred while your app was backgrounded. Although this crash cannot be avoided, you can mitigate its effects. For more details, check out https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin."

-ut

**Comment by shubhamnandanwar** [comment]
Thanks for your quick response. I was deleting objectbox database in my extended Application class. I moved this operation to my splash activity and it started working.
