### ISSUE TITLE
UnsatisfiedLink in Travis

### ISSUE THREAD

**Issue by LeoColman** [objectbox/objectbox-java#747]
## Issue Basics
- ObjectBox version (are using the latest version?): 2.3.4
- Reproducibility: Occurs when executing the tests in Travis-CI. [This issue was worked around in this project](https://github.com/Kerooker/rpg-npc-generator/pull/16)

### Description
I'm not completely sure how this bug was reproduced. It seems to be a missing library when running in Travis CI.

The complete stacktrace was:
> java.lang.UnsatisfiedLinkError: /home/travis/build/Kerooker/rpg-npc-generator/app/libobjectbox-jni-linux-x64.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/Kerooker/rpg-npc-generator/app/libobjectbox-jni-linux-x64.so)

## Misc
Searching on the web, I found a similar issue in [this stack exchange post](https://askubuntu.com/a/1130416/730581), which lead to [this resolution](https://discourse.gohugo.io/t/solved-hugo-v44-extended-and-relocation-errors-on-travis/13029/4). When this was applied to my build, it started working again.

Add this to your `before install`:
```
before_install:
  # This workaround is required to avoid libstdc++ errors while running "extended" hugo with SASS support.
  - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6
```

---- 
I'm not sure if it's ObjectBox's responsibility to fix this, but if anybody else comes through this issue, perhaps this guide helps.

**Comment by greenrobot-team** [comment]
`/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/Kerooker/rpg-npc-generator/app/libobjectbox-jni-linux-x64.so)` indicates that a required library was missing.

See also https://github.com/objectbox/objectbox-java/issues/245.

ObjectBox `2.3.x` supports Ubuntu 16.04 or newer. Your operating system may ship libraries older than supported. `ldd libobjectbox-jni-linux-x64.so` might get you more info.

**Comment by Kerooker** [comment]
I tried running with Trusty AND Xenial at Travis, and none of them worked. The only way to make it work was installing that different libstdc++6

If you think this has nothing to do with ObjectBox, and more to do with Travis, then we can close this issue

**Comment by greenrobot-team** [comment]
It should work on a clean xenial installation and definitely does on a clean bionic installation. You can verify by running `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` and checking if it includes `GLIBCXX_3.4.20`.

It's entirely possible that the Travis folks customize their images in a way that ship an older libstdc++ version than is the default.

Anyhow, travis recommends upgrading from trusty, it is out of support.
https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide
Also their Android guide is out-of-date. The Android Gradle plugin takes care of installing build tools since a while. You can look at the configuration of one of our other projects for inspiration (ignore the emulator stuff).
https://github.com/greenrobot/greenDAO/blob/master/.travis.yml

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
