### ISSUE TITLE
How to handle model symbol like “User_” in Java?

### ISSUE THREAD

**Issue by LeoK987** [objectbox/objectbox-java#907]
I tried to get an answer about this on stackoverflow, but no one cares answer, so I try it here.  Hope OK.

Say I have a model called "User" and it's under directory "models".

In my other modules where "User" is used, I need to `import xxx.yyy.models.User`.

But with my query statement:
```
List<User> joes = userBox.query(User_.firstName.equal("Joe"))
2 .build()
3 .find();
```
"User_" is used.  When I build the project, it complains that symbol "User_" is not found. It seems if I also import User_ in the module, like: `import xxx.yyy.models.User_`. Then it builds through.  But is this the right practice?  I don't see the documentation mentioning this.  Please clarify.

**Comment by greenrobot-team** [comment]
Did you tag your Stack Overflow question with `objectbox`? Otherwise we or others won't see it.

The `User_` file is generated during building your project. It exists in the same package as the entity class. And yes, you obviously need to import it to use it in a different package (that's how Java works, this is not specific to ObjectBox). See the docs for an explanation. https://docs.objectbox.io/queries

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
