### ISSUE TITLE
Exception in thread "main" io.objectbox.exception.DbException: DB's last entity ID 4 is higher than 1 from model

### ISSUE THREAD

**Issue by zhanglixing15133991761** [objectbox/objectbox-java#943]
:rotating_light: First, please check:
 - existing issues,
 - Docs https://docs.objectbox.io/
 - Troubleshooting page https://docs.objectbox.io/troubleshooting
 - FAQ page https://docs.objectbox.io/faq

**Describe the bug**
A clear and concise description in English of what the bug is.

**Basic info (please complete the following information):**
 - ObjectBox version (are you using the latest version?): [e.g. 2.7.0]
 - Reproducibility: [e.g. occurred once only | occasionally without visible pattern | always]
 - Device: [e.g. Galaxy S20]
 - OS: [e.g. Android 10]

**To Reproduce**
1. Put '...'
2. Make changes to '....'
3. See error

**Expected behavior**

**Code**
If applicable, add code to help explain your problem.
 - Include affected entity classes.
 - Please remove any unnecessary or confidential parts.
 - At best, link to or attach a project with a failing test.

**Logs, stack traces**
If applicable, add relevant logs, or a stack trace.
 - For __build issues__, use `--stacktrace` for the Gradle build (`./gradlew build --stacktrace`).
 - For __runtime errors__, check Android's Logcat (also check logs before the issue!).

**Additional context**
 - Is there anything special about your app?
 - May transactions or multi-threading play a role?
 - Did you find any workarounds to prevent the issue?

**Comment by greenrobot-team** [comment]
It would help if you would actually fill out the issue template...

See https://docs.objectbox.io/troubleshooting#dbexception-after-switching-git-branch-no-concurrent-data-model-modifications

**Comment by showwiki** [comment]
i come cross the same situation,  i solve it by the following code.  I delete all objectbox db file when exception
`try {
            boxStore = MyObjectBox.builder().androidContext(applicatioon).build();
        } catch (Exception e) {
            //兼容某些异常的情况，DB's last entity ID 16 is higher than 15 from model
            e.printStackTrace();
            try {
                String file = getFilesDir().getAbsolutePath() + File.separator + "objectbox";
                boolean result = new File(file).setWritable(true, false);
                Timber.d("%s", result);
                FileUtils.deleteAllFiles(new File(file));
                boxStore = MyObjectBox.builder().androidContext(PowerApp.instance).build();
            } catch (Exception ex) {
                ex.printStackTrace();
                CrashReport.postCatchedException(ex);
            }
        }`

**Comment by ajans** [comment]
I just had this problem after re-generating all default.json files, but after fresh-installing the app.
Turned out, the allowBackup-attribute in the AndroidManifest.xml was set to true, so the incompatible db-file was restored
during the fresh install.
interestingly, I only found this solution in a SO-thread for another problem (UID-mismatch):
https://stackoverflow.com/a/55008507/433421

Turns out, this problem is even explained in the official docs, but it would help in the future, if you could list some of the most-occuring error messages here in the official docs in connection with this problem / solution for better discoverability:
https://docs.objectbox.io/advanced/meta-model-ids-and-uids#the-nuke-option
